global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'airflow'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8080']  
  
  - job_name: 'nyc_taxi_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5055']  