name: CI/CD for Astro Airflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Astro CLI
        run: |
          curl -sSL https://install.astronomer.io | sudo bash
          astro version

      - name: Lint DAGs
        run: astro dev lint

      - name: Build Astro Airflow image
        run: |
          astro dev build
          # Re-tag the built image to a standard name
          docker tag $(docker images --format "{{.Repository}}:{{.Tag}}" | grep airflow) my-astro-airflow:latest

      - name: Run container and check metrics
        run: |
          docker run -d --name astro-test -p 8080:8080 -p 9102:9102 my-astro-airflow:latest
          sleep 20
          curl -f http://localhost:9102/metrics || (echo "❌ Metrics not working" && exit 1)
          docker stop astro-test
          docker rm astro-test
