name: CI/CD for Astro Airflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Astro CLI
        run: |
          curl -sSL https://install.astronomer.io | sudo bash
          astro version

      - name: Lint DAGs
        run: astro dev lint

      - name: Parse DAGs
        run: astro dev parse
